### ISSUE TITLE
Install `linter` automatically.

### ISSUE THREAD

**Issue by keplersj** [gepoch/linter-write-good#12]
By using [`atom-package-deps`](https://github.com/steelbrain/package-deps) you are able to install `linter` automatically on activation. This will allow new Atom users to install only your package and nothing else, removing one step from the installation process.

Please see AtomLinter/linter-ruby#38 for example.

**Comment by kepler0** [comment]
Closing due to package being actively developed, but issue has received no response.

**Comment by gepoch** [comment]
Hey! Sorry. Things have been insane at work. I haven't been able to keep an eye on my side projects as well.

Thanks for the issue. I'll be able to finish it this week, I think.
