### ISSUE TITLE
How to set up?

### ISSUE THREAD

**Issue by jjrob114** [gepoch/linter-write-good#14]
Hey, this is a really cool package, but it would be really awesome if you could actually explain how to set it up correctly in the Readme.

**Comment by gepoch** [comment]
Really, you just need to install the linter-write-good package, along with the linter package, which is already pointed out in the README.

Are there any specific parts of the setup that are unclear?

**Comment by jjrob114** [comment]
Hi there.  Thanks so much for the response.  :-)

Yeah, I'm pretty sure I installed everything correctly:

1) Installed globally with <code>npm install -g write-good</code>
2) Install the linter via <code>apm install linter-write-good</code>

But it doesn't seem to be working out of the box.  I tried it in a .md file with the same text shown in the example and nothing happens.  And I don't really understand how to configure it via custom node binaries or custom write-good scripts.  The write-good documentation helps a little from a basic node js perspective, but doesn't really say anything about how it connects with atom so it's very confusing for someone who hasn't programmed a node module like this before.

**Comment by jjrob114** [comment]
Ps. yes I restarted the text editor and I've gotten other linters working just fine. :-)

**Comment by gepoch** [comment]
The linter-write-good package will install its own copy of write-good into your atom package library. No need to ``npm install write-good``! That happens automatically when linter-write-good is installed. You shouldn't need to set the custom node binary or custom write-good scripts. Those are mostly there out of convention, and they might also be useful in testing customizations and such.

I'm assuming you've installed the base linter system with ``apm install linter``...

What versions of Atom and Linter are you using?

**Comment by jjrob114** [comment]
Cool.  I'm using Atom 1.3.2 and Linter 1.11.3

**Comment by jjrob114** [comment]
And yes I installed linter via the apm command.

**Comment by jjrob114** [comment]
Also, I'm running Windows 10.  The other linters I have installed are eslint and scss-lint.

**Comment by gepoch** [comment]
What types of file are you trying to lint? This linter only lints text formats (md, rst, latex, etc.)

**Comment by DanielAndreasen** [comment]
I also have some problems setting this up. I installed `linter` and this package with apm, and nothing happens.
I changed the default path to: `/home/daniel/.atom/packages/linter-write-good/node_modules/write-good/bin` (which it should be). If I call the executable in that path with a file `./write-good.js /path/to/file.md` everything seems to work.

The editor have been restarted a couple of times. The version of atom is: 1.1.0

**Comment by EmberQuill** [comment]
Same issue here. I installed linter and linter-write-good, but linter always says no issues with my writing even when I used a sentence from your example image in the readme.

**Comment by JohnMurga** [comment]
I also had this issue ...

For whatever reason it does not seem to work with the built in Node for me.
Specifying the v4.4.2 node executable I have installed made it work for me.

I did notice that it linted as I type, but that it lints against the saved file ...
Which seemed kinda wrong :wink:

**Comment by MaciejKlosowski** [comment]
Same issue here. I pretty much have everything installed as per the instructions:

Atom 1.7.4
linter 1.11.4
linter-write-good 0.6.1
OS: Windows 10

Linter says that everything is correct all the time I tested on a variety of different files (*.md, *.txt etc)

**Comment by Skinny77** [comment]
Same here sadly.

**Comment by strongway** [comment]
after upgrade linter to 1.11.16 today, write good is not working. Same here: No issues.

**Comment by JohnMurga** [comment]
Same here ... `apm install linter-write-good@0.6.1` to fix for me.
After I set node interpreter to "node" (which is in path).

**Comment by DanielAndreasen** [comment]
It wasn't working for me neither. Nut I just uninstalled and installed again. Then restarted atom, and it works now (using a LaTeX document). Thanks, looks cool!

**Comment by Iakubovich** [comment]
I had same issue too...
