### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by ChrisChinchilla** [gepoch/linter-write-good#16]
I LOVE this package, but for some reason it seems to have stopped working for me, and I'm not quite sure why. No bottom panel, no highlighted words.

What sort of debug information do you need to figure what's happened? I am frequently enabling and disabling all sorts of things, so there might have been some affect.

**Comment by ChrisChinchilla** [comment]
Actually, I did a window reload, and highlighting seems to be back, but not the summary pane at the bottom of the window, is that reliant on anything else being enabled?

**Comment by ChrisChinchilla** [comment]
Sorry, this was an issue with the linter package, some how the pane got disabled.

**Comment by gepoch** [comment]
@ChrisChinchilla Ah! Cool. Thanks for the update.
