### ISSUE TITLE
Support Asciidoc

### ISSUE THREAD

**Issue by codenameone** [gepoch/linter-write-good#17]
We use Asciidoc rather extensively for our docs and I'm not sure how I can turn on this plugin on Asciidoc. I know write-good doesn't support asciidoc properly but it's still better than nothing.

Is there some configuration file I can hack to get it to work?

**Comment by gepoch** [comment]
Hey! Thanks for the suggestion!

This is pretty easy to do, so I knocked it out really fast! https://github.com/gepoch/linter-write-good/commit/51ebc11cb6185e81303e191ed70a333de1cd1c62

That's released for you in 0.7.0. From my own testing everything looked good.

FYI, the write-good library that this linter uses is markdown specific, but it does okay for most nearly-plaintext formats. You mileage may vary! Let me know if you run into problems :)

This will make linter-write-good run on any file that Atom has identified as asciidoc. Basically, if language-asciidoc is running on your file, so should linter-write-good.

**Comment by codenameone** [comment]
Thanks! This is really great!
