### ISSUE TITLE
How do I refresh the linting?

### ISSUE THREAD

**Issue by jeffmacdonald** [gepoch/linter-write-good#20]
After I follow suggestions given to me by linter-write-good, they still appear in the bottom pane of Atom.How to re-scan, or make them go away?

**Comment by gepoch** [comment]
Hmm... It should be linting every time that you save. This isn't happening for me... You might want to check the settings for the "linter" package to make sure that things are set up correctly over there.

Also, what versions of linter-write-good and Atom are you running?

**Comment by jeffmacdonald** [comment]
Hi,

I’m running Linter 1.11.16, linter-pep8 1.3.2 , linter-write-good version 0.8.0  and Atom version 1.10.2

Here’s a short markdown document that I created with the original string “Just comment out the bad stuff” then after it told me, I removed the word “Just”

You can see that it is still telling me about the word “Just”. I’ve looked at all of the settings for the Linter plugin and they look reasonable. (re lints ever 300ms as I type)
