### ISSUE TITLE
How can I ignore certain file extensions?

### ISSUE THREAD

**Issue by tristan957** [gepoch/linter-write-good#22]
I don't need it linting my tex files.

**Comment by Arcanemagus** [comment]
You can tell [Linter](https://atom.io/packages/Linter) itself to ignore file extensions like that in its settings, note however that that will make it ignore those files for _all_ providers.

**Comment by gepoch** [comment]
Yep. That looks like your best option.

You could also adjust the alert type to info in the linter-write-good settings to distinguish it from any other linters you might use, which could be acceptable.
