### ISSUE TITLE
How to configure to only process certain file extensions?

### ISSUE THREAD

**Issue by theangrydev** [gepoch/linter-write-good#23]
For example, I want to only process .md files

**Comment by gepoch** [comment]
Unfortunately the way linter works, there's no way to change this without altering the package source. You can turn linter completely off for specific formats, but the files that are linted are part of linter source: https://github.com/gepoch/linter-write-good/blob/master/lib/init.coffee#L52

You can turn off all linters for a particular format inside of the "linter" project's settings.
