### ISSUE TITLE
Toggling plugin on/off

### ISSUE THREAD

**Issue by philip** [gepoch/linter-write-good#25]
I'm new to atom, and Linter, but toggling individual Linter plugins on/off does not appear common. I'm not sure why that is but this is a request for easy `linter-write-good` toggling.

At present, it seems we must either disable Linter (which I assume means disabling all Linter plugins), or disable an individual Linter plugin in the Package manager. Seems a simpler way would exist.

If the ability to easily enable/disable this plugin at runtime won't be added then please expand the README to explain how we enable/disable this plugin, and how to know if it's enabled or disabled for the current document. Thanks :)

**Comment by Arcanemagus** [comment]
@philip You'll want to follow https://github.com/steelbrain/linter/issues/1165 where discussion about this is happening (and where the eventual change will have to be made).
