### ISSUE TITLE
Upgrade write-good package

### ISSUE THREAD

**Issue by Vorror** [gepoch/linter-write-good#27]
Can you release a new build using an updated version write-good? I'm looking for e-prime support that was just added.

**Comment by gepoch** [comment]
See #25

**Comment by gepoch** [comment]
@Vorror Looks like they haven't actually release 1.10.3 which has the eprime feature in it! It's been tested, but no build has been released yet. Once they make the release, I'll upgrade linter-write-good. I'll keep the ticket open until then.

**Comment by gepoch** [comment]
@Vorror Done! Out in v0.9.0

**Comment by gepoch** [comment]
P.S. I've chosen to leave it disable by default, as it is in the write-good project. You'll need to set the `--yes-eprime` flag in the package settings if you'd like to enable it. See the readme for details.

Thanks
