### ISSUE TITLE
E-prime linting doesn’t support smart quotes

### ISSUE THREAD

**Issue by hilton** [gepoch/linter-write-good#32]
E-prime linting doesn’t report errors for words including _to be_ that use contractions containing curly/smart/typographer’s quotations marks.

To reproduce:

1. enable E-prime linting (Settings / Additional arguments / `--yes-eprime`)
2. save a document containing the words `isn’t isn't`

Expected: both words trigger the `is a form of 'to be'` linting error/warning.

Observed: `isn’t` doesn’t result in an error.

**Comment by gepoch** [comment]
Hey @hilton linter-write-good is just a wrapper for the upstream library write-good! Please file your issue there https://github.com/btford/write-good
