### ISSUE TITLE
Latex support

### ISSUE THREAD

**Issue by kmisiunas** [gepoch/linter-write-good#6]
Could you add latex support please.

**Comment by gepoch** [comment]
Great idea! I'll get that out momentarily.

**Comment by gepoch** [comment]
Okay, should be supported in 0.4.0 using the language-latex plugin :)

**Comment by gepoch** [comment]
Hold up. Missed a bunch. 0.4.1 coming out shortly.

**Comment by gepoch** [comment]
Alright! Try it now :)

**Comment by kmisiunas** [comment]
great! that was fast.

It does not seem to automatically pick up that Latex should be Lint-ed, and the "Lint" command does not help. I got it to work by switching to to Markdown and then back to Latex. Any ideas why?

**Comment by gepoch** [comment]
Hmm. Does it work on a reload of atom? It may have just been some state of the linter module getting updated.

**Comment by kmisiunas** [comment]
Works beautifully! It is amazing. Thank so much for adding the Latex support

**Comment by gepoch** [comment]
Thanks for filing the ticket! I hope it comes in handy :)
